_target_: pytorch_lightning.Trainer
_partial_: True
logger: ${logger}
max_epochs: ${max_epochs}
accelerator: ${accelerator}
devices: ${devices}
num_sanity_val_steps: 0
precision: ${precision}
accumulate_grad_batches: ${accumulate_grad_batches}
deterministic: true