batch_size: 256
num_workers: 12
max_epochs: 200
lr: 0.001

precision: 16
accelerator: cuda
devices: [0]
accumulate_grad_batches: 1

num_classes: 136
height: 256
width: 256
crop_height: 224
crop_width: 224
normalize_keypoints: true

hydra:
  run:
    dir: ./outputs/${model.model_name}/${now:%Y-%m-%d}-${now:%H-%M-%S}

defaults:
  - _self_
  - model: default
  - datamodule: default
  - optim: adamw
  - criterion: mse
  - lr_scheduler: plateau
  - callbacks: default
  - metrics: default
  - paths: default
  - logger: tensorboard
  - augmentations: default
  - trainer: default