train:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: ${height}
      width: ${width}
      interpolation: 3
    - _target_: albumentations.ShiftScaleRotate
      p: 0.5
    - _target_: albumentations.PixelDropout
      p: 0.5
    - _target_: albumentations.Blur
      p: 0.5
    - _target_: albumentations.ColorJitter
      p: 0.5
    - _target_: albumentations.CLAHE
      p: 0.5
    - _target_: albumentations.Normalize
    - _target_: albumentations.pytorch.ToTensorV2
  
  keypoint_params: 
    _target_: albumentations.KeypointParams
    format: xy 
    remove_invisible: false


test:
  _target_: albumentations.Compose
  transforms:
    - _target_: albumentations.Resize
      height: ${height}
      width: ${width}
      interpolation: 3
    - _target_: albumentations.Normalize
    - _target_: albumentations.pytorch.ToTensorV2
  
  keypoint_params: 
    _target_: albumentations.KeypointParams
    format: xy 
    remove_invisible: false