- _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}"
  name: "train"
  log_graph: False
  default_hp_metric: True
  prefix: ""

- _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${paths.output_dir}"
  name: "valid"
  log_graph: False
  default_hp_metric: True
  prefix: ""
  